const artPiecesData = [
  {
    id: "1",
    slug: "voilette-blues",
    name: "Voilette Blues",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Abstract",
    technique: "Oil",
    imageUrl: "/assets/violette-blues.jpg",
    heightReal: 100,
    widthReal: 100,
  },

  {
    id: "2",
    slug: "milky-way",
    name: "Milky Way",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "/assets/milky-way.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "3",
    slug: "ocean-scene",
    name: "Ocean Scene",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "/assets/ocean-side.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "4",
    slug: "mona-lisa",
    name: "Mona Lisa",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Portrait",
    technique: "Oil",
    imageUrl: "/assets/mona-lisa.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "5",
    slug: "forest-walk",
    name: "Forest Walk",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "/assets/forest-walk.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "6",
    slug: "fishermens-bay",
    name: "Fishermens Bay",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "/assets/fishermens-bay.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "7",
    slug: "nordic-snow-hut",
    name: "Nordic Snow Hut",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "/assets/nordic-snow-hut.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "8",
    slug: "spilled-coffee",
    name: "Spilled Coffee",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",

    category: "Abstract",
    technique: "Acryl",
    imageUrl: "/assets/spilled-coffee.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "9",
    slug: "florenz",
    name: "Florenz",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Acryl",
    imageUrl: "/assets/florenz.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "10",
    slug: "blue-blues",
    name: "Blue Blues",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Abstract",
    technique: "Acryl",
    imageUrl: "/assets/blue-blues.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "11",
    slug: "rainbow-blues",
    name: "Rainbow Blues",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Abstract",
    technique: "Oil",
    imageUrl: "/assets/rainbow-blues.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "12",
    slug: "grunge",
    name: "Grunge",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Abstract",
    technique: "Oil",
    imageUrl: "/assets/grunge.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "13",
    slug: "mountain-in-vietnam",
    name: "Mountain In Vietnam",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "/assets/mountain-in-vietnam.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "14",
    slug: "izmir-mountain",
    name: "Izmir Mountain",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "/assets/izmir-mountain.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "15",
    slug: "ephesus",
    name: "Ephesus",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "/assets/ephesus.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "16",
    slug: "mersin-bay-1811",
    name: "Mersin Bay 1811",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "/assets/mersin-bay-1811.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "17",
    slug: "stormy-north",
    name: "Stormy North",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "/assets/stormy-north.jpg",
    heightReal: 100,
    widthReal: 100,
  },
  {
    id: "18",
    slug: "alps",
    name: "Alps",
    date: 2021,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "/assets/alps.jpg",
    heightReal: 100,
    widthReal: 100,
  },
];

export default artPiecesData;
