const artPiecesData = [
  {
    id: "1",
    slug: "voilette-blues",
    name: "Voilette Blues",
    date: "2000",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Abstract",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2019/04/26/17/47/color-4158152_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },

  {
    id: "2",
    slug: "milky-way",
    name: "Milky Way",
    date: "2003",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2012/11/28/08/54/milky-way-67504_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "3",
    slug: "ocean-scene",
    name: "Ocean Scene",
    date: "2002",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/02/24/18/15/andreas-achenbach-85762_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "4",
    slug: "mona-lisa",
    name: "Mona Lisa",
    date: "2006",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Portrait",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/01/05/21/02/art-74050_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "5",
    slug: "forest-walk",
    name: "Forest Walk",
    date: "2009",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2018/09/20/17/01/birch-3691340_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "6",
    slug: "fishermens-bay",
    name: "Fishermens Bay",
    date: "2010",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/02/24/18/32/sebastian-pether-85797_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "7",
    slug: "nordic-snow-hut",
    name: "Nordic Snow Hut",
    date: "2011",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/03/03/19/46/george-durrie-89656_1280.jpg",
    date: "2021",
    widthReal: "100",
  },
  {
    id: "test",
    slug: "nordic-snow-hut",
    name: "Nordic Snow Hut",
    date: "2011",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Test2",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/03/03/19/46/george-durrie-89656_1280.jpg",
    date: "2021",
    widthReal: "100",
  },
  {
    id: "test3",
    slug: "nordic-snow-hut",
    name: "Nordic Snow Hut",
    date: "2011",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Test2",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/03/03/19/46/george-durrie-89656_1280.jpg",
    date: "2021",
    widthReal: "100",
  },
  {
    id: "8",
    slug: "spilled-coffee",
    name: "Spilled Coffee",
    date: "2012",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",

    category: "Abstract",
    technique: "Acryl",
    imageUrl: "https://cdn.pixabay.com/photo/2017/06/01/02/17/abstract-2362258_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "9",
    slug: "florenz",
    name: "Florenz",
    date: "2013",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Acryl",
    imageUrl: "https://cdn.pixabay.com/photo/2014/05/11/17/30/painting-342116_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "10",
    slug: "blue-blues",
    name: "Blue Blues",
    date: "2014",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Abstract",
    technique: "Acryl",
    imageUrl: "https://cdn.pixabay.com/photo/2020/03/09/10/23/color-4915201_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "11",
    slug: "rainbow-blues",
    name: "Rainbow Blues",
    date: "2015",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Abstract",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2018/02/04/09/09/art-3129359_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "12",
    slug: "grunge",
    name: "Grunge",
    date: "2016",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Abstract",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2022/10/22/01/56/abstract-7538251_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "13",
    slug: "mountain-in-vietnam",
    name: "Mountain In Vietnam",
    date: "2017",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/02/19/18/10/robert-duncanson-83429_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "14",
    slug: "izmir-mountain",
    name: "Izmir Mountain",
    date: "2018",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/02/24/18/32/ramon-alsina-85796_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "15",
    slug: "ephesus",
    name: "Ephesus",
    date: "2019",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/02/14/03/57/christen-kobk-81509_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "16",
    slug: "mersin-bay-1811",
    name: "Mersin Bay 1811",
    date: "2021",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/03/09/19/14/ivan-alvazovsky-91987_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "17",
    slug: "stormy-north",
    name: "Stormy North",
    date: "2022",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Impression",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/03/08/15/51/johan-dahl-91590_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
  {
    id: "18",
    slug: "alps",
    name: "Alps",
    date: "2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    category: "Landscape",
    technique: "Oil",
    imageUrl: "https://cdn.pixabay.com/photo/2013/03/02/22/21/caspar-friedrich-89414_1280.jpg",
    heightReal: "100",
    widthReal: "100",
  },
];

export default artPiecesData;
